### ISSUE TITLE
[DEVOPS] Migration old wesite to the new one

### ISSUE THREAD

**Issue by nicolasbonnet** [Dojo-Makoto/Dojo-Makoto.github.io#5]
To redirect and redirect SEO ranked to the new website, we need to apply 301 rules for the old website.

##TODO

- [x] list all available url from http://makoto.dojo.free.fr/

```xml
<urlset xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!--
 created with Free Online Sitemap Generator www.xml-sitemaps.com 
-->
<url>
<loc>http://makoto.dojo.free.fr/</loc>
<lastmod>2021-10-20T21:50:42+00:00</lastmod>
<priority>1.00</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/index.php</loc>
<lastmod>2021-10-20T21:50:42+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/discipline.html</loc>
<lastmod>2020-08-20T10:05:34+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/professeur.html</loc>
<lastmod>2020-08-20T10:05:36+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/uchi.html</loc>
<lastmod>2021-08-29T16:04:04+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/fonctionnement.html</loc>
<lastmod>2020-08-20T10:05:35+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/zen.html</loc>
<lastmod>2020-09-20T14:48:25+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/galerie.html</loc>
<lastmod>2020-08-20T10:05:35+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/actualite.html</loc>
<lastmod>2021-08-29T05:11:36+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/ados.html</loc>
<lastmod>2020-08-20T10:05:34+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/pratique.html</loc>
<lastmod>2021-08-29T05:11:37+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/index_en.php</loc>
<lastmod>2021-10-20T21:50:42+00:00</lastmod>
<priority>0.80</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/discipline_en.html</loc>
<lastmod>2020-08-20T10:08:20+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/professeur_en.html</loc>
<lastmod>2020-08-20T10:08:22+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/uchi_en.html</loc>
<lastmod>2021-08-29T16:04:03+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/fonctionnement_en.html</loc>
<lastmod>2020-08-20T10:08:20+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/zen_en.html</loc>
<lastmod>2020-09-20T14:50:27+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/galerie_en.html</loc>
<lastmod>2020-08-20T10:08:20+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/actualite_en.html</loc>
<lastmod>2021-08-29T05:11:36+00:00</lastmod>
<priority>0.64</priority>
</url>
<url>
<loc>http://makoto.dojo.free.fr/pratique_en.html</loc>
<lastmod>2021-08-29T05:11:37+00:00</lastmod>
<priority>0.64</priority>
</url>
</urlset>
```

- [x] search docs to be sure to create rules from best practice
 
- [x] find solution for .php files on makoto.dojo.free.fr
	- remove php file
	- verify all URL redirection do not find a 404 ...

- [x] apply theses rules in .htaccess from http://makoto.dojo.free.fr/

In logic we have to do this
- Activate rewrite rules:
```bash
Options +FollowSymLinks
RewriteEngine on
```
- Apply generic rule to redirect all page to the new ones:
```txt
RedirectMatch 301 ^(.*)$ https://www.aikido-marseille-makoto.info/
```

⚠️ 
```txt
Vous devez absolument supprimer ou remplacer tous les liens pointant vers une page 404 pendant le processus de la refonte. De plus, on vous recommande fortement de mettre à jour tous les liens qui pointent vers des pages redirigées afin qu’ils pointent vers la nouvelle page finale. Vous ne voulez pas vous retrouver avec des chaînes de redirection après la migration
```

- [ ] #12
